-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.daily_trainings (
  id text NOT NULL,
  user_id uuid NOT NULL,
  training_date date NOT NULL,
  total_sessions integer NOT NULL DEFAULT 0,
  total_duration integer NOT NULL DEFAULT 0,
  total_exercises integer NOT NULL DEFAULT 0,
  completed_sessions integer NOT NULL DEFAULT 0,
  intent_breakdown jsonb,
  muscle_breakdown jsonb,
  is_streak_day boolean NOT NULL DEFAULT false,
  achievements ARRAY DEFAULT ARRAY[]::text[],
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT daily_trainings_pkey PRIMARY KEY (id),
  CONSTRAINT daily_trainings_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.deeplink_clicks (
  id text NOT NULL,
  deeplink_id text NOT NULL,
  clicked_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ip_address text,
  user_agent text,
  referer text,
  CONSTRAINT deeplink_clicks_pkey PRIMARY KEY (id),
  CONSTRAINT deeplink_clicks_deeplink_id_fkey FOREIGN KEY (deeplink_id) REFERENCES public.deeplinks(id)
);
CREATE TABLE public.deeplinks (
  id text NOT NULL,
  code text NOT NULL UNIQUE,
  target_type USER-DEFINED NOT NULL,
  target_id text NOT NULL,
  created_by uuid,
  expires_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT deeplinks_pkey PRIMARY KEY (id)
);
CREATE TABLE public.equipment (
  id text NOT NULL,
  code text NOT NULL UNIQUE,
  name text NOT NULL,
  category USER-DEFINED NOT NULL,
  recognizable boolean NOT NULL DEFAULT false,
  recognition_labels ARRAY DEFAULT ARRAY[]::text[],
  recognition_confidence double precision NOT NULL DEFAULT 0.85,
  icon_url text NOT NULL,
  image_url text,
  display_order integer NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT equipment_pkey PRIMARY KEY (id)
);
CREATE TABLE public.exercise_equipment (
  exercise_id text NOT NULL,
  equipment_id text NOT NULL,
  is_required boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT exercise_equipment_pkey PRIMARY KEY (exercise_id, equipment_id),
  CONSTRAINT exercise_equipment_exercise_id_fkey FOREIGN KEY (exercise_id) REFERENCES public.exercises(id),
  CONSTRAINT exercise_equipment_equipment_id_fkey FOREIGN KEY (equipment_id) REFERENCES public.equipment(id)
);
CREATE TABLE public.exercise_scenarios (
  exercise_id text NOT NULL,
  scenario_id text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT exercise_scenarios_pkey PRIMARY KEY (exercise_id, scenario_id),
  CONSTRAINT exercise_scenarios_exercise_id_fkey FOREIGN KEY (exercise_id) REFERENCES public.exercises(id),
  CONSTRAINT exercise_scenarios_scenario_id_fkey FOREIGN KEY (scenario_id) REFERENCES public.scenarios(id)
);
CREATE TABLE public.exercises (
  id text NOT NULL,
  code text NOT NULL UNIQUE,
  name text NOT NULL,
  primary_muscle USER-DEFINED NOT NULL,
  secondary_muscles ARRAY DEFAULT ARRAY[]::text[],
  intent_type USER-DEFINED NOT NULL,
  difficulty USER-DEFINED NOT NULL,
  description jsonb NOT NULL,
  default_duration integer NOT NULL,
  default_sets integer NOT NULL DEFAULT 1,
  duration_type USER-DEFINED NOT NULL,
  demo_image_url text,
  demo_video_url text,
  tags ARRAY DEFAULT ARRAY[]::text[],
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT exercises_pkey PRIMARY KEY (id)
);
CREATE TABLE public.rarity_table (
  id text NOT NULL,
  equipment_id text NOT NULL,
  equipment_code text NOT NULL,
  week_start date NOT NULL,
  rarity_score double precision NOT NULL,
  rarity_level USER-DEFINED NOT NULL,
  data_source USER-DEFINED NOT NULL DEFAULT 'WEEKLY_TABLE'::"DataSource",
  region text,
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT rarity_table_pkey PRIMARY KEY (id),
  CONSTRAINT rarity_table_equipment_id_fkey FOREIGN KEY (equipment_id) REFERENCES public.equipment(id)
);
CREATE TABLE public.scenario_equipment (
  scenario_id text NOT NULL,
  equipment_id text NOT NULL,
  is_common boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT scenario_equipment_pkey PRIMARY KEY (scenario_id, equipment_id),
  CONSTRAINT scenario_equipment_scenario_id_fkey FOREIGN KEY (scenario_id) REFERENCES public.scenarios(id),
  CONSTRAINT scenario_equipment_equipment_id_fkey FOREIGN KEY (equipment_id) REFERENCES public.equipment(id)
);
CREATE TABLE public.scenarios (
  id text NOT NULL,
  code text NOT NULL UNIQUE,
  name text NOT NULL,
  noise_tolerance USER-DEFINED,
  space_requirement USER-DEFINED,
  icon_url text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT scenarios_pkey PRIMARY KEY (id)
);
CREATE TABLE public.session_exercises (
  id text NOT NULL,
  session_id text NOT NULL,
  exercise_id text NOT NULL,
  sequence_order integer NOT NULL,
  duration integer NOT NULL,
  sets integer NOT NULL DEFAULT 1,
  is_completed boolean NOT NULL DEFAULT false,
  actual_duration integer,
  started_at timestamp with time zone,
  ended_at timestamp with time zone,
  paused_times integer NOT NULL DEFAULT 0,
  skip_reason text,
  difficulty_felt USER-DEFINED,
  comfort_level integer,
  effectiveness_rating integer,
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT session_exercises_pkey PRIMARY KEY (id),
  CONSTRAINT session_exercises_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.workout_sessions(id),
  CONSTRAINT session_exercises_exercise_id_fkey FOREIGN KEY (exercise_id) REFERENCES public.exercises(id)
);
CREATE TABLE public.share_cards (
  id text NOT NULL,
  user_id uuid NOT NULL,
  session_id text NOT NULL UNIQUE,
  card_image_url text NOT NULL,
  card_template text NOT NULL,
  card_data jsonb NOT NULL,
  rarity USER-DEFINED NOT NULL,
  equipment_series text NOT NULL,
  rarity_score double precision NOT NULL,
  data_source USER-DEFINED NOT NULL DEFAULT 'WEEKLY_TABLE'::"DataSource",
  special_tags ARRAY DEFAULT ARRAY[]::text[],
  city_edition text,
  theme_week text,
  share_text character varying,
  is_public boolean NOT NULL DEFAULT true,
  share_count integer NOT NULL DEFAULT 0,
  view_count integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT share_cards_pkey PRIMARY KEY (id),
  CONSTRAINT share_cards_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT share_cards_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.workout_sessions(id)
);
CREATE TABLE public.theme_week_participations (
  id text NOT NULL,
  user_id uuid NOT NULL,
  theme_week_id text NOT NULL,
  status text NOT NULL DEFAULT 'JOINED'::text,
  joined_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  completed_at timestamp with time zone,
  exercises_completed integer NOT NULL DEFAULT 0,
  target_exercises integer NOT NULL,
  progress_percent double precision NOT NULL DEFAULT 0.0,
  reward_earned boolean NOT NULL DEFAULT false,
  reward_claimed_at timestamp with time zone,
  related_sessions ARRAY DEFAULT ARRAY[]::text[],
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT theme_week_participations_pkey PRIMARY KEY (id),
  CONSTRAINT theme_week_participations_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT theme_week_participations_theme_week_id_fkey FOREIGN KEY (theme_week_id) REFERENCES public.theme_weeks(id)
);
CREATE TABLE public.theme_weeks (
  id text NOT NULL,
  title text NOT NULL,
  code text NOT NULL UNIQUE,
  description character varying,
  equipment_code text NOT NULL,
  target_exercise_count integer NOT NULL DEFAULT 3,
  start_date date NOT NULL,
  end_date date NOT NULL,
  reward_type text NOT NULL,
  reward_data jsonb,
  status text NOT NULL DEFAULT 'UPCOMING'::text,
  is_visible boolean NOT NULL DEFAULT true,
  display_order integer NOT NULL DEFAULT 0,
  total_participants integer NOT NULL DEFAULT 0,
  total_completions integer NOT NULL DEFAULT 0,
  completion_rate double precision NOT NULL DEFAULT 0.0,
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT theme_weeks_pkey PRIMARY KEY (id)
);
CREATE TABLE public.user_preferences (
  id text NOT NULL,
  user_id uuid NOT NULL,
  preference_type text NOT NULL,
  preference_key text NOT NULL,
  preference_value double precision NOT NULL,
  usage_count integer NOT NULL DEFAULT 0,
  success_rate double precision NOT NULL DEFAULT 0.0,
  average_rating double precision,
  last_used_at timestamp with time zone,
  first_used_at timestamp with time zone NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT user_preferences_pkey PRIMARY KEY (id),
  CONSTRAINT user_preferences_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL,
  email text UNIQUE,
  name text,
  avatar_url text,
  total_workouts integer NOT NULL DEFAULT 0,
  total_duration_sec integer NOT NULL DEFAULT 0,
  current_streak integer NOT NULL DEFAULT 0,
  longest_streak integer NOT NULL DEFAULT 0,
  preferred_intents ARRAY DEFAULT ARRAY[]::"IntentType"[],
  preferred_difficulty USER-DEFINED,
  preferred_duration integer,
  avoid_equipment ARRAY DEFAULT ARRAY[]::text[],
  streak_reminder boolean NOT NULL DEFAULT true,
  theme_week_reminder boolean NOT NULL DEFAULT true,
  quiet_hours_start text,
  quiet_hours_end text,
  hide_real_photos boolean NOT NULL DEFAULT true,
  auto_blur_faces boolean NOT NULL DEFAULT true,
  allow_data_sync boolean NOT NULL DEFAULT false,
  language text NOT NULL DEFAULT 'zh'::text,
  theme text NOT NULL DEFAULT 'auto'::text,
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT users_pkey PRIMARY KEY (id)
);
CREATE TABLE public.workout_sessions (
  id text NOT NULL,
  user_id uuid NOT NULL,
  intent_type USER-DEFINED NOT NULL,
  scenario_id text,
  target_muscles ARRAY DEFAULT ARRAY[]::"PrimaryMuscle"[],
  total_duration integer NOT NULL,
  difficulty USER-DEFINED NOT NULL,
  is_silent boolean NOT NULL DEFAULT false,
  status USER-DEFINED NOT NULL DEFAULT 'PENDING'::"SessionStatus",
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  actual_duration integer,
  follow_mode boolean NOT NULL DEFAULT false,
  current_step integer NOT NULL DEFAULT 0,
  pause_count integer NOT NULL DEFAULT 0,
  skip_count integer NOT NULL DEFAULT 0,
  is_offline boolean NOT NULL DEFAULT false,
  ambient_noise USER-DEFINED,
  used_space USER-DEFINED,
  rating integer,
  feedback character varying,
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT workout_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT workout_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT workout_sessions_scenario_id_fkey FOREIGN KEY (scenario_id) REFERENCES public.scenarios(id)
);